@port = http://127.0.0.1:8000/api/posts
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmYWQxMTlmYzk2N2I5MDAxNzliY2QwYyIsImlhdCI6MTYwNTQ2MzE1NSwiZXhwIjozMTcxNDk5MDU1NTV9.a-kwdjfl2YEojB5U687deO8K2UpOh-Zga23Nqik3FQM
@postid = 5fb28286543501147816ba5c

GET {{port}} HTTP/1.1
###
POST {{port}}/{{postid}}/dislike HTTP/1.1
auth-token : {{token}}
###

POST {{port}}/{{postid}}/comment HTTP/1.1
auth-token : {{token}}
Content-Type: application/json

{
    "text" : "Second comment of man"
}
###
DELETE {{port}}/comment/{{postid}} HTTP/1.1
auth-token : {{token}}
Content-Type: application/json

{
    "commentID" : "5fb2833989dbf11ff43cd597"
}